import Head from "next/head";
// import { useState, useEffect } from "react";
import style from "../styles/Home.module.css";
import CurrencyRupeeIcon from '@mui/icons-material/CurrencyRupee';
import { useRouter } from "next/router";
import Grid from '@mui/material/Grid';
import { Card,CardActionArea,CardContent,CardMedia, Chip, Paper, Typography } from "@mui/material";
import { useSelector,useDispatch } from "react-redux";
import { getCart } from "../redux/actions/cartAction";
import { useEffect } from "react";
import Cookies from "js-cookie";
import { Box, Container } from "@mui/system";

export default function Home({user }) {
  const dispatch = useDispatch()

  // useEffect(()=>{
  //   if(!Cookies.get('token')){
  //     dispatch({type:CLEAR_CART})
  //   }
  // },[user.value])

  return (
    <>
      <Head>
        <title>BetterMart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>       
            <Box sx={{maxWidth:"100%",height:"60vh"}}>
            <Typography className={style.heading} sx={{fontSize: "2.5rem",fontFamily:'Playfair Display' }} variant="h1">Welcome to bettermart</Typography>
              <img src="/pexels-karolina.jpg" alt="Photo by Ksenia Chernaya" style={{width: "100%",height:"100%", overflowY:"hidden"}}/>
            </Box> 
      </main>
    </>
  );
}
