import Head from "next/head";
import style from "../styles/Home.module.css";
import { Box, Card, Paper, Typography } from "@mui/material";
import { Inter } from "@next/font/google";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect } from "react";
import images from "../utils/images";

const inter = Inter({ subsets: ["latin"] });

const categories = [
  "home-decoration",
  "groceries",
  "womens-dresses",
  "womens-shoes",
  "mens-shirts",
  "mens-shoes",
  "furniture",
  "mens-watches",
  "womens-bags",
  "womens-jewellery",
];

export default function Home({ user }) {
    const  router = useRouter()
    const fetching =async(category)=>{
      router.push(`/products/category/${category}`)
    }
 


  return (
    <>
      <Head>
        <title>BetterMart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <Box sx={{ maxWidth: "100%", height: "100%" }}>
          <Box className={style.heading}>
            <Typography
              sx={{ fontSize: "3.5vmax", fontFamily: "Playfair Display" }}
              variant="h1"
            >
              Welcome to bettermart
            </Typography>
            <Typography
              sx={{ marginTop: "1rem", fontSize: "1.8vmax" }}
              variant="h6"
            >
              Shop everything at one place
            </Typography>
          </Box>
          <Image
            className={style.homeimage}
            src="/image1.jpg"
            alt="Photo by Ksenia Chernaya"
            style={{ objectFit: "fill", width: "100%" }}
            width={1000}
            height={700}
          />
        </Box>
        <Box sx={{ width: "100%", minHeight: "30rem", padding: "1rem" ,display:"flex",flexDirection:"row",flexWrap:"wrap",justifyContent:"center" ,gap:"15px"}}>
          {categories.map((category,index)=>{
            return(
              <Box key={category} onClick={()=>fetching(category)} className={style.category} >
              <Image src={images[index]} alt={index} height={150} width={170} style={{objectFit:"cover"}}/>
                <Typography variant="body1" >{category}</Typography>
              </Box>
            )
          })}
        </Box>
      </main>
    </>
  );
}
